### ISSUE TITLE
Include all necessary nginx config snippets

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/galaxy-operator#77]
We still need to include these though:

[pulp_ansible snippet](https://github.com/pulp/pulp_ansible/blob/main/pulp_ansible/app/webserver_snippets/nginx.conf)
[pulp_container snippet](https://github.com/pulp/pulp_container/blob/main/pulp_container/app/webserver_snippets/nginx.conf)

See https://github.com/ansible/galaxy-operator/pull/75 for context.

**Comment by kurokobo** [comment]
@rooftopcellist @dsavineau 
Hi, thanks for reviewing and merging my PR #75.

I had reviewed all three snippets that added in [pulp-oci-images for pulp/galaxy-web](https://github.com/pulp/pulp-oci-images/blob/latest/images/galaxy-minimal/stable/Containerfile.webserver#L6-L8) and I found most of `location` directives in the snippets already routed correctly by existing `location /` directives, that's why add only two `location` directives in my PR.

Adding additional snippets as they are is okay but they are defined to use `pulp-api` and  `pulp-content` as `proxy_pass`, so to make finding upstream change easier, we should use these snippets as they are and should modify `upstream` from `galaxy-*` to `pulp-*` though.

By the way could you please let me know the repository where actual `Containerfile` for `galaxy` and `galaxy-ui` images are stored? Want to see if there is a room to add snippets dynamically.
I can't find any GHA that builds and pushes them to quay.io in neither `galaxy_ng` repo nor `ansible-hub-ui` repo. I think something is happend in [ansible-hub-ui-build](https://github.com/RedHatInsights/ansible-hub-ui-build) and related Jenkins pipelines but I also can't find pipeline definitions for that under `RedHatInsights` org 😞

**Comment by rooftopcellist** [comment]
o/ @kurokobo 
The Dockerfiles are here:
* https://github.com/ansible/galaxy_ng/blob/master/Dockerfile.rhel8
* https://github.com/ansible/ansible-hub-ui/blob/master/community/Dockerfile (80% sure on this, will confirm)

We no longer build out of the `pulp-oci-images` repo, that is reserved for the pulp team.  Now galaxy and the galaxy-operator is maintained by the Ansible team internally.  


I am not entirely sure where the build actually happens. I'll reach out to those teams.  I don't see anythign configured in GHA's or quay.io.  It could be built and pushed by our internal AWX or Jenkins instance.

**Comment by kurokobo** [comment]
@rooftopcellist 
Thanks for letting me know.
From the community's perspective, since the builds are processed inside undisclosed pipeline and this causes lack of transparency, it's a bit difficult to guarantee that the images on quay.io are indeed built by a publicly available Dockerfile and that no unintended modifications have been made 😞
Hope the pipeline would be open (Of course I know it's extremely difficult). Anyway thanks for sharingthe background!
